### ISSUE TITLE
App长时间不用，在恢复，推送报错React: Calling JS function after bridge has been destroyed

### ISSUE THREAD

**Issue by wulaizi** [cnhongwei/react-native-mqtt-v3#4]
以上报错锁定到代码
<img width="1215" alt="image" src="https://github.com/cnhongwei/react-native-mqtt-v3/assets/33690834/78a1cb8e-baba-4e85-a782-9d1764450ee0">
sendEvent(reactApplicationContext, MESSAGE_PREFIX + mqttAndroidClient.getClientId(), writableMapOf("topic", topic, "base64Message", Base64.encodeToString(message.getPayload(), Base64.NO_WRAP)));
收到了数据，但是从这里开始，就发送不了数据到RN了，

**Comment by cnhongwei** [comment]
你是开发模式下？还是产品模式下？如果是开发模式下，代码reload了吗？

**Comment by wulaizi** [comment]
> 你是开发模式下？还是产品模式下？如果是开发模式下，代码reload了吗？

两者都会出现，
开发模式，
在logcat下是可以明显看到socket是接收到了数据的，
只是数据从原生这边“没有派发给RN”，监听方法里也并没有
报错React: Calling JS function after bridge has been destroyed
release包下也是如此
当然两者正常情况下都是没问题的，
但是有时候测试一会不用app，
就出现了接收不到，必须重启app

**Comment by wulaizi** [comment]
测试手机android 9 华为 鸿蒙系统

**Comment by wulaizi** [comment]
![18121704426222_ pic](https://github.com/cnhongwei/react-native-mqtt-v3/assets/33690834/9d4640ff-8b5b-4301-8a7a-26d9cb1e16e0)
这里是locat日志，可以看到数据原生的接收到了
https://stackoverflow.com/questions/45972220/react-calling-js-function-after-bridge-has-been-destroyed-how-to-find-which 找到个类似报错

**Comment by wulaizi** [comment]
刚才尝试了下ios 也有同样的问题，
来回切后台，
或者切页面都不会导致接收不到，
很久不用app后，似乎就再也收不到数据了，
但是原生端这边是有数据的，没有派发到给RN

**Comment by cnhongwei** [comment]
好的。我看看能复现不。你的RN是什么版本？你大约多少时间后有问题？

**Comment by wulaizi** [comment]
好的。我看看能复现不。你的RN是什么版本？你大约花了多少时间后有问题？

RN  0.72.6
真机 ios 11 系统17  
android 9
就几分钟吧，在当前，或者切换到其他界面停留几分钟，后然后手动 或者自动锁屏， 再次激活app 应该就可以复现，
以下是我的代码
`import {
  createMqttClient,
  type MqttOptions,
  type MqttClient,
} from 'react-native-mqtt-v3';
import UserActions from '../stores/actions/UserActions';
// @ts-ignore
import {decode} from 'base-64';
import {SocketDataRes} from '../net/response/SocketDataRes';
import {reduxStore} from '../App';
import GameActions from '../stores/actions/GameActions';
export type MqttObserver = (message: any) => void;
export default class MqttClientUtil {
  static MQTT_HOST = '链接地址';
  static MQTT_PORT = 443;
  static MQTT_PROTOCOL = 'wss';
  static MQTT_TOPIC = 'myTopic';
  private observers: Array<MqttObserver> = new Array();
  private static ins: MqttClientUtil;
  public static client: MqttClient;
  private static username: string;
  private static password: string;
  public static getIns(): MqttClientUtil {
    if (!this.ins) {
      this.ins = new MqttClientUtil();
    }
    return this.ins;
  }
  static async initOptions(
    username: string,
    password: string,
  ): Promise<MqttOptions> {
    return {
      clientId: await UserActions.getMQTTClientId(),
      host: MqttClientUtil.MQTT_HOST,
      port: MqttClientUtil.MQTT_PORT,
      protocol: MqttClientUtil.MQTT_PROTOCOL as any,
      username: username,
      password: password,
    };
  }

  static isOkinit(username: string, password: string) {
    return (
      !MqttClientUtil.client ||
      username !== MqttClientUtil.username ||
      password !== MqttClientUtil.password
    );
  }

  async init(username: string, password: string) {
    if (MqttClientUtil.isOkinit(username, password)) {
      createMqttClient(await MqttClientUtil.initOptions(username, password))
        .then(client => {
          MqttClientUtil.client = client;
          MqttClientUtil.username = username;
          MqttClientUtil.password = password;
          client.connect();
          client.onConnect(() => {
            console.log('---------MQTT连接上---------');
          });
          client.onDisconnect(({message}) => {});
          client.onMessage(({topic, base64Message}) => {
            const plainText = decode(base64Message);
            if (plainText) {
              try {
                let data = JSON.parse(plainText);
                GameActions.socketPushBet(data);
                GameActions.outRoom(data);
                GameActions.checkBalance(data);
                MqttClientUtil.getIns().mqttNotifyObservers(data);
              } catch (error) {}
            }
          });
        })
        .catch(err => {});
    }
  }

  public addMqttObserver(onMqttObserver: MqttObserver) {
    if (this.observers.indexOf(onMqttObserver) == -1) {
      this.observers.push(onMqttObserver);
    }
  }

  public mqttNotifyObservers(message: SocketDataRes) {
    this.observers.forEach(observer => {
      observer(message);
    });
  }

  public removeMqttObserver(onMqttMessage: MqttObserver) {
    const index = this.observers.indexOf(onMqttMessage);
    if (index !== -1) {
      this.observers.splice(index, 1);
    }
  }

  static subscribe() {
    if (MqttClientUtil.client) {
      let roomId = reduxStore.getState().commonReducers.onlineRoom?.id;
      MqttClientUtil.client.subscribe(`${MqttClientUtil.MQTT_TOPIC}${roomId}`);
    }
  }

  static unsubscribe() {
    if (MqttClientUtil.client) {
      MqttClientUtil.client.unsubscribe(MqttClientUtil.MQTT_TOPIC);
    }
  }
}
`

**Comment by wulaizi** [comment]
不知道跟这个有关系没
https://stackoverflow.com/questions/33758390/react-native-android-activity-onpause-onresume

Android Activity
onPause/onResume
ios如此

**Comment by wulaizi** [comment]
<img width="983" alt="image" src="https://github.com/cnhongwei/react-native-mqtt-v3/assets/33690834/1b715a09-9242-4237-8c9b-948a796c9aa8">

**Comment by wulaizi** [comment]
> <img alt="图像" width="983" src="https://private-user-images.githubusercontent.com/33690834/294863004-1b715a09-9242-4237-8c9b-948a796c9aa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDc3OTMsIm5iZiI6MTcwNDcwNzQ5MywicGF0aCI6Ii8zMzY5MDgzNC8yOTQ4NjMwMDQtMWI3MTVhMDktOTI0Mi00MjM3LThjOWItOTQ4YTc5NmM5YWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5NTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5Y2QzNzg1MzVlNDkwMDFiZjc3YzY1YjBhZDA0NzlmNjIwOTE0NTA3NDEwYWYzMzc3ZTMzM2NkOWY3NzhmNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WMjSo5WXHb4xPsTZrCWf7pGE-4qJebTPHsZwpSRZg4Q">

然后一直收不到了

**Comment by cnhongwei** [comment]
我测试了一下，如果reconnect后，不会出现React: Calling JS function after bridge has been destroyed这个错误，我按这个错误搜索，都是RN的一些相差信息，不知道是不是你RN版本的问题。
但是我测试了，reconnect之后，我这里不是消息转不给RN，而是好像subscibe丢了，没有收到消息，我得再仔细测试一下，如果是这个问题，我还得看看如何解决，CocoaMQTT和paho.mqtt.java有很多地方不一致，我是先按paho.mqtt.java写的流程，写完后，使用CocoaMQTT时，发现很多地方很难抹平。

**Comment by wulaizi** [comment]
> 我测试了一下，如果重新连接后，不会出现React: Calling JS function afterbridge has was destroy这个错误，我按这个错误搜索，都是RN的一些外侧信息，不是不知道你RN版本的问题 。我测试了，重新连接之后，我这里不是消息转不给RN，而是好像subscibe丢了，没有收到消息，我得再仔细测试一下，如果是这个问题，我还得看看如何解决，CocoaMQTT和paho.mqtt.java有很多地方不一致，我是先按paho.mqtt.java写的流程，写完后，使用CocoaMQTT时，发现很多地方很难抹平。

不知道这个报错是否是开发模式，reload后出现的 ，
但是可以确定正式环境下， 
如果有以下场景 复现如下:
 假设后端socket如果15秒不交互，
 就会断开连接，
  那么我们一般解决方案是心跳， 但是，如果用户切后台1分钟，
  也就是1分钟没有交互，再打开时必然断开，就会出现2个问题
   1、如你所说 ，订阅丢失
   2、收不到重连回调(实际上原生端已打印重连成功) 此问题我目前已解决 
         解决方案 :因为订阅丢失导致的收不到回调， 我这边启动时重新订阅，
         但是重新订阅，可能你还没重连成功   就 “订阅在先了”，
         所以App启动了，我会连续订阅10次，每隔1秒一次解决
